FROM maven:3.9.11-eclipse-temurin-17 AS build

WORKDIR /workspace

COPY pom.xml .
COPY src ./src

RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /workspace/target/coudy-0.0.1-SNAPSHOT.jar /app/app.jar

EXPOSE 9096

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
